kind: curvefs
global:
  report_usage: true
  data_dir: ${home}/curvefs/data/${service_role}
  log_dir: ${home}/curvefs/logs/${service_role}
  container_image: opencurvedocker/curvefs:latest
  variable:
    home: /tmp
    machine1: server-host1
    machine2: serevr-host2
    machine3: server-host3

etcd_services:
  config:
    listen.ip: ${service_host}
    listen.port: 2380
    listen.client_port: 2379
  deploy:
    - host: ${machine1}
    - host: ${machine2}
    - host: ${machine3}

mds_services:
  config:
    listen.ip: ${service_host}
    listen.port: 6700
    listen.dummy_port: 7700
  deploy:
    - host: ${machine1}
    - host: ${machine2}
    - host: ${machine3}

metaserver_services:
  config:
    listen.ip: ${service_host}
    listen.port: 6800
    listen.external_port: 7800
    global.enable_external_server: true
    metaserver.loglevel: 0
  deploy:
    - host: ${machine1}
    - host: ${machine2}
    - host: ${machine3}
      config:
        metaserver.loglevel: 0
