kind: curvebs
global:
  container_image: opencurvedocker/curvebs:v1.2.6
  log_dir: ${home}/logs/${service_role}${service_replicas_sequence}
  data_dir: ${home}/data/${service_role}${service_replicas_sequence}
  s3.nos_address: <>
  s3.snapshot_bucket_name: <>
  s3.ak: <>
  s3.sk: <>
  variable:
    home: /tmp
    machine1: server-host1
    machine2: server-host2
    machine3: server-host3

etcd_services:
  config:
    listen.ip: ${service_host}
    listen.port: 2380
    listen.client_port: 2379
  deploy:
    - host: ${machine1}
    - host: ${machine2}
    - host: ${machine3}

mds_services:
  config:
    listen.ip: ${service_host}
    listen.port: 6666
    listen.dummy_port: 6667
  deploy:
    - host: ${machine1}
    - host: ${machine2}
    - host: ${machine3}

chunkserver_services:
  config:
    listen.ip: ${service_host}
    listen.port: 82${format_instances_sequence}  # 8200,8201,8202
    data_dir: /data/chunkserver${service_instances_sequence}  # /data/chunkserver0, /data/chunksever1
    copysets: 100
  deploy:
    - host: ${machine1}
      instances: 3
    - host: ${machine2}
      instances: 3
    - host: ${machine3}
      instances: 3

snapshotclone_services:
  config:
    listen.ip: ${service_host}
    listen.port: 5555
    listen.dummy_port: 8081
    listen.proxy_port: 8080
  deploy:
    - host: ${machine1}
    - host: ${machine2}
    - host: ${machine3}
